### PR TITLE
Modernise markup and styles

### PR DESCRIPTION
**Pull request by fofr**
I recommend reviewing this commit by commit, and using `?w=1` to ignore whitespace (HTML indentation changes create noise). Having somebody check out the mobile/tablet views will also help.

Two critical changes;
- Fix all IE8, IE7 and IE6 styles
- Add missing help-notice styles so that FCO advice not to travel to a country is big and clear

Clean up:
- Remove all legacy styles – most styles are provided by static and components
- Update from legacy grid to new grid
- Allow views to set a page class based on format, similar to `government-frontend`
- Replace the grey summary/updated pattern with the metadata component
- Use govspeak component for summary content
- Stop using title component for part titles

Once https://github.com/alphagov/static/pull/730 is deployed the last commit in this PR can be reverted.

https://trello.com/c/Lv5JExC0/283-multipage-frontend-cleanup-1-day
# Country Summary

| Before | After |
| --- | --- |
| travel-advice-before | travel-advice-after |
# Part

| Before | After |
| --- | --- |
| travel-advice-health-before | travel-advice-health-after |
# Help notices
## Before

screen shot 2016-02-09 at 12 34 19
## After

screen shot 2016-02-09 at 12 49 50
# Older Internet Explorer
## IE before

screen shot 2016-02-09 at 14 25 53
## IE after

screen shot 2016-02-09 at 14 35 45

cc @dsingleton @steventux

### CODE REVIEW

**Comment by jamiecobbett** [comment]
In the screenshots, the summary has "Latest update: Latest update: ".

**Comment by fofr** [comment]
@jamiecobbett Good spot, it looks like it's hardcoded into the content item: 

``` json
"change_description": "Latest update: Summary - there have been a significant number of attacks in Kabul in recent months, including on the Afghan news agency and military bases and convoys "
```

**Comment by binaryberry** [comment]
At the moment in Chrome and Firefox, when reducing the window to minimum width, a horizontal bar appears towards the top, between the country name and summary. This change moves that bar down to after the heading links and "Get updates". Is that intentional?

**Comment by fofr** [comment]
The "Latest update" text is added by publishers: 
screen shot 2016-02-10 at 14 54 07

**Comment by fofr** [comment]
@binaryberry That's a bug with the live version on smaller viewports – the floating items aren't being cleared correctly.

**Comment by dsingleton** [comment]
Overall LGTM :+1: 

Doubling "latest update" feels like a regression we shouldn't introduce. Could we strip that in the presenter, or finding a phrasing of the label that avoids the issue? Feels like an issue with the Publisher UI that editors are adding a "latest" prefix, but fixing that is outside the scope of this PR.

Otherwise happy to merge.

**Comment by binaryberry** [comment]
@fofr , and this fixes the bug, got it! 
LGTM too! I compared the old and new versions in Firefox and Chrome, Desktop (various window sizes) and various mobile devices (iPad, Nexus, Samsung, etc.). I see some differences, but they are improvements: changed related-items column size and darker metadata font colour improve readability, and the horizontal bar bug is fixed.

**Comment by fofr** [comment]
Duplicate "Latest update" fixed in 9745dcd

**Comment by dsingleton** [comment]
Merged as this is an overall improvement, and fixes a couple of production-affecting issues so we should :shipit: ASAP.

**Pull request merged**
